version: '3'

services:
  asira_geomapping:
    build: .
    ports:
      - 8002:8002
    image: asira_geomapping:development
    volumes:
      - ./:/go/src/asira_geomapping
    hostname: localhost
    environment:
      - APPNAME=asira_geomapping
      - ENV=dev
    container_name: asira_geomapping
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: asirauser
      POSTGRES_PASSWORD: asirapass
      POSTGRES_DB: asira_db
    ports:
      - 5432:5432
    container_name: postgres_db
    networks: 
      - asira_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8010:8080
    container_name: asira_adminer
    hostname: "adminer.local"

  portainer:
    image: portainer/portainer
    container_name: "portainer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock --no-auth
    ports:
      - 9000:9000

networks:
  default:
    external:
      name: asira_net