development:
  react_cors: true
  database:
    table: asira_geomapping
    username: asirauser
    password: asirapass
    host: "127.0.0.1"
    port: "5432"
    maxlifetime: 30
    idle_conns: 10
    open_conns: 100
    sslmode: disable
    logmode: true
    timezone: Asia/Jakarta
  clients:
    admin: YWRtaW46YWRtaW5rZXk= #admin:adminkey
    client: Y2xpZW50OmNsaWVudGdlbw== # client:clientgeo
  jwt:
    duration: 10080 # in minutes
    jwt_secret: sXQ8jUMpueOvN5P3cdCR

staging:

production: